INSERT INTO Enrolled VALUES ('ST0098', 2, 'B.Sc', 'Physics' );
INSERT INTO Enrolled VALUES ('ST0061', 2, 'B.Sc', 'Physics' );
INSERT INTO Enrolled VALUES ('ST0073', 2, 'B.Sc', 'Physics' );
INSERT INTO Enrolled VALUES ('ST0065', 2, 'B.Sc', 'Physics' );
INSERT INTO Enrolled VALUES ('ST0049', 2, 'B.Sc', 'Physics' );
INSERT INTO Enrolled VALUES ('ST0023', 2, 'B.Sc', 'Chemistry' );
INSERT INTO Enrolled VALUES ('ST0007', 2, 'B.Sc', 'Chemistry' );
INSERT INTO Enrolled VALUES ('ST0050', 2, 'B.Sc', 'Chemistry' );
INSERT INTO Enrolled VALUES ('ST0022', 2, 'B.Sc', 'Chemistry' );
INSERT INTO Enrolled VALUES ('ST0087', 2, 'B.Sc', 'Chemistry' );
INSERT INTO Enrolled VALUES ('ST0017', 2, 'B.Tech', 'Computer Science' );
INSERT INTO Enrolled VALUES ('ST0012', 2, 'B.Tech', 'Computer Science' );
INSERT INTO Enrolled VALUES ('ST0047', 2, 'B.Tech', 'Computer Science' );
INSERT INTO Enrolled VALUES ('ST0045', 2, 'B.Tech', 'Computer Science' );
INSERT INTO Enrolled VALUES ('ST0100', 2, 'B.Tech', 'Computer Science' );
INSERT INTO Enrolled VALUES ('ST0066', 2, 'B.Tech', 'Mechanical' );
INSERT INTO Enrolled VALUES ('ST0064', 2, 'B.Tech', 'Mechanical' );
INSERT INTO Enrolled VALUES ('ST0039', 2, 'B.Tech', 'Mechanical' );
INSERT INTO Enrolled VALUES ('ST0053', 2, 'B.Tech', 'Mechanical' );
INSERT INTO Enrolled VALUES ('ST0001', 2, 'B.Tech', 'Mechanical' );
INSERT INTO Enrolled VALUES ('ST0075', 2, 'B.Tech', 'Electronics' );
INSERT INTO Enrolled VALUES ('ST0029', 2, 'B.Tech', 'Electronics' );
INSERT INTO Enrolled VALUES ('ST0077', 2, 'B.Tech', 'Electronics' );
INSERT INTO Enrolled VALUES ('ST0051', 2, 'B.Tech', 'Electronics' );
INSERT INTO Enrolled VALUES ('ST0048', 2, 'B.Tech', 'Electronics' );
INSERT INTO Enrolled VALUES ('ST0090', 4, 'B.Sc', 'Physics' );
INSERT INTO Enrolled VALUES ('ST0036', 4, 'B.Sc', 'Physics' );
INSERT INTO Enrolled VALUES ('ST0086', 4, 'B.Sc', 'Physics' );
INSERT INTO Enrolled VALUES ('ST0055', 4, 'B.Sc', 'Physics' );
INSERT INTO Enrolled VALUES ('ST0041', 4, 'B.Sc', 'Physics' );
INSERT INTO Enrolled VALUES ('ST0062', 4, 'B.Sc', 'Chemistry' );
INSERT INTO Enrolled VALUES ('ST0080', 4, 'B.Sc', 'Chemistry' );
INSERT INTO Enrolled VALUES ('ST0014', 4, 'B.Sc', 'Chemistry' );
INSERT INTO Enrolled VALUES ('ST0069', 4, 'B.Sc', 'Chemistry' );
INSERT INTO Enrolled VALUES ('ST0046', 4, 'B.Sc', 'Chemistry' );
INSERT INTO Enrolled VALUES ('ST0037', 4, 'B.Tech', 'Computer Science' );
INSERT INTO Enrolled VALUES ('ST0067', 4, 'B.Tech', 'Computer Science' );
INSERT INTO Enrolled VALUES ('ST0027', 4, 'B.Tech', 'Computer Science' );
INSERT INTO Enrolled VALUES ('ST0015', 4, 'B.Tech', 'Computer Science' );
INSERT INTO Enrolled VALUES ('ST0032', 4, 'B.Tech', 'Computer Science' );
INSERT INTO Enrolled VALUES ('ST0082', 4, 'B.Tech', 'Mechanical' );
INSERT INTO Enrolled VALUES ('ST0043', 4, 'B.Tech', 'Mechanical' );
INSERT INTO Enrolled VALUES ('ST0068', 4, 'B.Tech', 'Mechanical' );
INSERT INTO Enrolled VALUES ('ST0034', 4, 'B.Tech', 'Mechanical' );
INSERT INTO Enrolled VALUES ('ST0072', 4, 'B.Tech', 'Mechanical' );
INSERT INTO Enrolled VALUES ('ST0085', 4, 'B.Tech', 'Electronics' );
INSERT INTO Enrolled VALUES ('ST0097', 4, 'B.Tech', 'Electronics' );
INSERT INTO Enrolled VALUES ('ST0020', 4, 'B.Tech', 'Electronics' );
INSERT INTO Enrolled VALUES ('ST0013', 4, 'B.Tech', 'Electronics' );
INSERT INTO Enrolled VALUES ('ST0094', 4, 'B.Tech', 'Electronics' );
INSERT INTO Enrolled VALUES ('ST0006', 6, 'B.Sc', 'Physics' );
INSERT INTO Enrolled VALUES ('ST0030', 6, 'B.Sc', 'Physics' );
INSERT INTO Enrolled VALUES ('ST0076', 6, 'B.Sc', 'Physics' );
INSERT INTO Enrolled VALUES ('ST0052', 6, 'B.Sc', 'Physics' );
INSERT INTO Enrolled VALUES ('ST0035', 6, 'B.Sc', 'Physics' );
INSERT INTO Enrolled VALUES ('ST0024', 6, 'B.Sc', 'Chemistry' );
INSERT INTO Enrolled VALUES ('ST0056', 6, 'B.Sc', 'Chemistry' );
INSERT INTO Enrolled VALUES ('ST0099', 6, 'B.Sc', 'Chemistry' );
INSERT INTO Enrolled VALUES ('ST0042', 6, 'B.Sc', 'Chemistry' );
INSERT INTO Enrolled VALUES ('ST0044', 6, 'B.Sc', 'Chemistry' );
INSERT INTO Enrolled VALUES ('ST0002', 6, 'B.Tech', 'Computer Science' );
INSERT INTO Enrolled VALUES ('ST0060', 6, 'B.Tech', 'Computer Science' );
INSERT INTO Enrolled VALUES ('ST0003', 6, 'B.Tech', 'Computer Science' );
INSERT INTO Enrolled VALUES ('ST0040', 6, 'B.Tech', 'Computer Science' );
INSERT INTO Enrolled VALUES ('ST0083', 6, 'B.Tech', 'Computer Science' );
INSERT INTO Enrolled VALUES ('ST0079', 6, 'B.Tech', 'Mechanical' );
INSERT INTO Enrolled VALUES ('ST0091', 6, 'B.Tech', 'Mechanical' );
INSERT INTO Enrolled VALUES ('ST0089', 6, 'B.Tech', 'Mechanical' );
INSERT INTO Enrolled VALUES ('ST0078', 6, 'B.Tech', 'Mechanical' );
INSERT INTO Enrolled VALUES ('ST0054', 6, 'B.Tech', 'Mechanical' );
INSERT INTO Enrolled VALUES ('ST0004', 6, 'B.Tech', 'Electronics' );
INSERT INTO Enrolled VALUES ('ST0009', 6, 'B.Tech', 'Electronics' );
INSERT INTO Enrolled VALUES ('ST0025', 6, 'B.Tech', 'Electronics' );
INSERT INTO Enrolled VALUES ('ST0071', 6, 'B.Tech', 'Electronics' );
INSERT INTO Enrolled VALUES ('ST0093', 6, 'B.Tech', 'Electronics' );
INSERT INTO Enrolled VALUES ('ST0005', 4, 'B.Tech', 'Electronics' );
INSERT INTO Enrolled VALUES ('ST0008', 4, 'B.Sc', 'Physics' );
INSERT INTO Enrolled VALUES ('ST0010', 2, 'B.Tech', 'Mechanical' );
INSERT INTO Enrolled VALUES ('ST0011', 6, 'B.Sc', 'Chemistry' );
INSERT INTO Enrolled VALUES ('ST0016', 2, 'B.Tech', 'Electronics' );
INSERT INTO Enrolled VALUES ('ST0018', 2, 'B.Tech', 'Mechanical' );
INSERT INTO Enrolled VALUES ('ST0019', 2, 'B.Sc', 'Chemistry' );
INSERT INTO Enrolled VALUES ('ST0021', 4, 'B.Tech', 'Mechanical' );
INSERT INTO Enrolled VALUES ('ST0026', 6, 'B.Tech', 'Mechanical' );
INSERT INTO Enrolled VALUES ('ST0028', 2, 'B.Sc', 'Chemistry' );
INSERT INTO Enrolled VALUES ('ST0031', 6, 'B.Tech', 'Mechanical' );
INSERT INTO Enrolled VALUES ('ST0033', 2, 'B.Sc', 'Chemistry' );
INSERT INTO Enrolled VALUES ('ST0038', 2, 'B.Sc', 'Physics' );
INSERT INTO Enrolled VALUES ('ST0057', 6, 'B.Tech', 'Mechanical' );
INSERT INTO Enrolled VALUES ('ST0058', 2, 'B.Tech', 'Mechanical' );
INSERT INTO Enrolled VALUES ('ST0059', 2, 'B.Sc', 'Chemistry' );
INSERT INTO Enrolled VALUES ('ST0063', 2, 'B.Tech', 'Electronics' );
INSERT INTO Enrolled VALUES ('ST0070', 4, 'B.Tech', 'Computer Science' );
INSERT INTO Enrolled VALUES ('ST0074', 4, 'B.Tech', 'Computer Science' );
INSERT INTO Enrolled VALUES ('ST0081', 2, 'B.Tech', 'Mechanical' );
INSERT INTO Enrolled VALUES ('ST0084', 4, 'B.Tech', 'Computer Science' );
INSERT INTO Enrolled VALUES ('ST0088', 4, 'B.Sc', 'Physics' );
INSERT INTO Enrolled VALUES ('ST0092', 6, 'B.Tech', 'Mechanical' );
INSERT INTO Enrolled VALUES ('ST0095', 6, 'B.Sc', 'Physics' );
INSERT INTO Enrolled VALUES ('ST0096', 4, 'B.Sc', 'Chemistry' );
