INSERT INTO Instructor VALUES ('IN0032', 'Robert Morgan', 'B.Tech', 'Computer Science');
INSERT INTO Instructor VALUES ('IN0001', 'Matthew Johnston', 'B.Tech', 'Computer Science');
INSERT INTO Instructor VALUES ('IN0009', 'William Padilla', 'B.Tech', 'Computer Science');
INSERT INTO Instructor VALUES ('IN0013', 'Mr. Larry Jackson', 'B.Tech', 'Computer Science');
INSERT INTO Instructor VALUES ('IN0024', 'Brendan Robinson', 'B.Tech', 'Computer Science');
INSERT INTO Instructor VALUES ('IN0029', 'Joanne Cole', 'B.Tech', 'Computer Science');
INSERT INTO Instructor VALUES ('IN0038', 'Sonya Jones', 'B.Tech', 'Computer Science');
INSERT INTO Instructor VALUES ('IN0011', 'Justin Peterson', 'B.Tech', 'Computer Science');
INSERT INTO Instructor VALUES ('IN0021', 'Christian Crosby', 'B.Tech', 'Electronics');
INSERT INTO Instructor VALUES ('IN0002', 'Beth Gonzalez', 'B.Tech', 'Electronics');
INSERT INTO Instructor VALUES ('IN0035', 'Clarence Kaufman', 'B.Tech', 'Electronics');
INSERT INTO Instructor VALUES ('IN0026', 'Taylor Patel', 'B.Tech', 'Electronics');
INSERT INTO Instructor VALUES ('IN0017', 'Erin Salinas', 'B.Tech', 'Electronics');
INSERT INTO Instructor VALUES ('IN0023', 'Marvin Terrell', 'B.Tech', 'Electronics');
INSERT INTO Instructor VALUES ('IN0014', 'Mary Ramos', 'B.Tech', 'Electronics');
INSERT INTO Instructor VALUES ('IN0030', 'Amber Carlson', 'B.Tech', 'Electronics');
INSERT INTO Instructor VALUES ('IN0039', 'Seth Baker', 'B.Tech', 'Mechanical');
INSERT INTO Instructor VALUES ('IN0020', 'Christopher Thornton', 'B.Tech', 'Mechanical');
INSERT INTO Instructor VALUES ('IN0016', 'Troy Nelson', 'B.Tech', 'Mechanical');
INSERT INTO Instructor VALUES ('IN0004', 'Jason Holt', 'B.Tech', 'Mechanical');
INSERT INTO Instructor VALUES ('IN0007', 'Michael Pham', 'B.Tech', 'Mechanical');
INSERT INTO Instructor VALUES ('IN0031', 'Michael Reese', 'B.Tech', 'Mechanical');
INSERT INTO Instructor VALUES ('IN0008', 'Christopher Bauer', 'B.Tech', 'Mechanical');
INSERT INTO Instructor VALUES ('IN0018', 'Joshua Ross', 'B.Tech', 'Mechanical');
INSERT INTO Instructor VALUES ('IN0036', 'Kevin Trujillo', 'B.Sc', 'Physics');
INSERT INTO Instructor VALUES ('IN0040', 'Bryan Gillespie', 'B.Sc', 'Physics');
INSERT INTO Instructor VALUES ('IN0022', 'Destiny Grant', 'B.Sc', 'Physics');
INSERT INTO Instructor VALUES ('IN0010', 'Mark Jefferson', 'B.Sc', 'Physics');
INSERT INTO Instructor VALUES ('IN0027', 'Leonard Carter', 'B.Sc', 'Physics');
INSERT INTO Instructor VALUES ('IN0033', 'Laurie Holmes', 'B.Sc', 'Physics');
INSERT INTO Instructor VALUES ('IN0037', 'Anthony Wilson', 'B.Sc', 'Physics');
INSERT INTO Instructor VALUES ('IN0019', 'Emily Rodriguez', 'B.Sc', 'Physics');
INSERT INTO Instructor VALUES ('IN0005', 'Adrian Hernandez', 'B.Sc', 'Chemistry');
INSERT INTO Instructor VALUES ('IN0012', 'James Diaz', 'B.Sc', 'Chemistry');
INSERT INTO Instructor VALUES ('IN0015', 'Andrea Patrick', 'B.Sc', 'Chemistry');
INSERT INTO Instructor VALUES ('IN0006', 'Katrina Jacobs', 'B.Sc', 'Chemistry');
INSERT INTO Instructor VALUES ('IN0025', 'Alyssa Tucker', 'B.Sc', 'Chemistry');
INSERT INTO Instructor VALUES ('IN0003', 'Lauren Wilson', 'B.Sc', 'Chemistry');
INSERT INTO Instructor VALUES ('IN0028', 'Joseph Shaw', 'B.Sc', 'Chemistry');
INSERT INTO Instructor VALUES ('IN0034', 'Veronica Cook', 'B.Sc', 'Chemistry');
