INSERT INTO Subject VALUES ('EE202', 'Signal Processing', 'B.Tech', 'Electronics', 40, 2, 4);
INSERT INTO Subject VALUES ('EE204', 'Circuit Design', 'B.Tech', 'Electronics', 35, 2, 2);
INSERT INTO Subject VALUES ('EE206', 'Microcontrollers', 'B.Tech', 'Electronics', 48, 2, 6);
INSERT INTO Subject VALUES ('EE208', 'Field Theory', 'B.Tech', 'Electronics', 41, 2, 6);
INSERT INTO Subject VALUES ('EE210', 'Communication Systems', 'B.Tech', 'Electronics', 31, 2, 3);
INSERT INTO Subject VALUES ('EE402', 'Digital Communications', 'B.Tech', 'Electronics', 49, 4, 2);
INSERT INTO Subject VALUES ('EE404', 'Instrumentation', 'B.Tech', 'Electronics', 31, 4, 5);
INSERT INTO Subject VALUES ('EE406', 'Control Systems', 'B.Tech', 'Electronics', 39, 4, 2);
INSERT INTO Subject VALUES ('EE408', 'Electromagnetic Waves', 'B.Tech', 'Electronics', 37, 4, 4);
INSERT INTO Subject VALUES ('EE410', 'Electronic Materials', 'B.Tech', 'Electronics', 30, 4, 3);
INSERT INTO Subject VALUES ('EE602', 'Power Electronics', 'B.Tech', 'Electronics', 35, 6, 4);
INSERT INTO Subject VALUES ('EE604', 'VLSI Design', 'B.Tech', 'Electronics', 37, 6, 3);
INSERT INTO Subject VALUES ('EE606', 'Digital Systems', 'B.Tech', 'Electronics', 45, 6, 6);
INSERT INTO Subject VALUES ('EE608', 'Antenna Theory', 'B.Tech', 'Electronics', 41, 6, 5);
INSERT INTO Subject VALUES ('EE610', 'Wireless Systems', 'B.Tech', 'Electronics', 35, 6, 2);
INSERT INTO Subject VALUES ('ME202', 'Thermodynamics', 'B.Tech', 'Mechanical', 35, 2, 3);
INSERT INTO Subject VALUES ('ME204', 'Solid Mechanics', 'B.Tech', 'Mechanical', 37, 2, 2);
INSERT INTO Subject VALUES ('ME206', 'Fluid Mechanics', 'B.Tech', 'Mechanical', 38, 2, 6);
INSERT INTO Subject VALUES ('ME208', 'Engineering Materials', 'B.Tech', 'Mechanical', 30, 2, 2);
INSERT INTO Subject VALUES ('ME210', 'Manufacturing Technology', 'B.Tech', 'Mechanical', 44, 2, 3);
INSERT INTO Subject VALUES ('ME402', 'Theory of Machines', 'B.Tech', 'Mechanical', 34, 4, 4);
INSERT INTO Subject VALUES ('ME404', 'Thermal Engineering', 'B.Tech', 'Mechanical', 46, 4, 5);
INSERT INTO Subject VALUES ('ME406', 'Manufacturing Processes', 'B.Tech', 'Mechanical', 44, 4, 5);
INSERT INTO Subject VALUES ('ME408', 'Metrology', 'B.Tech', 'Mechanical', 38, 4, 4);
INSERT INTO Subject VALUES ('ME410', 'Machine Dynamics', 'B.Tech', 'Mechanical', 49, 4, 3);
INSERT INTO Subject VALUES ('ME602', 'Computer-Aided Design', 'B.Tech', 'Mechanical', 44, 6, 5);
INSERT INTO Subject VALUES ('ME604', 'Heat Transfer', 'B.Tech', 'Mechanical', 45, 6, 6);
INSERT INTO Subject VALUES ('ME606', 'Refrigeration', 'B.Tech', 'Mechanical', 30, 6, 6);
INSERT INTO Subject VALUES ('ME608', 'Gas Dynamics', 'B.Tech', 'Mechanical', 39, 6, 5);
INSERT INTO Subject VALUES ('ME610', 'Mechatronics', 'B.Tech', 'Mechanical', 31, 6, 2);
INSERT INTO Subject VALUES ('CS202', 'Data Structures', 'B.Tech', 'Computer Science', 30, 2, 4);
INSERT INTO Subject VALUES ('CS204', 'Computer Organization', 'B.Tech', 'Computer Science', 46, 2, 3);
INSERT INTO Subject VALUES ('CS206', 'Operating Systems', 'B.Tech', 'Computer Science', 42, 2, 3);
INSERT INTO Subject VALUES ('CS208', 'Discrete Mathematics', 'B.Tech', 'Computer Science', 43, 2, 6);
INSERT INTO Subject VALUES ('CS210', 'Database Management', 'B.Tech', 'Computer Science', 35, 2, 2);
INSERT INTO Subject VALUES ('CS402', 'Software Engineering', 'B.Tech', 'Computer Science', 34, 4, 3);
INSERT INTO Subject VALUES ('CS404', 'Computer Networks', 'B.Tech', 'Computer Science', 47, 4, 2);
INSERT INTO Subject VALUES ('CS406', 'Theory of Computation', 'B.Tech', 'Computer Science', 39, 4, 3);
INSERT INTO Subject VALUES ('CS408', 'Compiler Design', 'B.Tech', 'Computer Science', 30, 4, 2);
INSERT INTO Subject VALUES ('CS410', 'Web Programming', 'B.Tech', 'Computer Science', 46, 4, 5);
INSERT INTO Subject VALUES ('CS602', 'Artificial Intelligence', 'B.Tech', 'Computer Science', 32, 6, 5);
INSERT INTO Subject VALUES ('CS604', 'Computer Graphics', 'B.Tech', 'Computer Science', 44, 6, 4);
INSERT INTO Subject VALUES ('CS606', 'Information Security', 'B.Tech', 'Computer Science', 43, 6, 3);
INSERT INTO Subject VALUES ('CS608', 'Distributed Systems', 'B.Tech', 'Computer Science', 30, 6, 6);
INSERT INTO Subject VALUES ('CS610', 'Cloud Computing', 'B.Tech', 'Computer Science', 44, 6, 3);
INSERT INTO Subject VALUES ('PH202', 'Classical Mechanics', 'B.Sc', 'Physics', 38, 2, 5);
INSERT INTO Subject VALUES ('PH204', 'Electricity', 'B.Sc', 'Physics', 47, 2, 5);
INSERT INTO Subject VALUES ('PH206', 'Mathematical Methods', 'B.Sc', 'Physics', 44, 2, 6);
INSERT INTO Subject VALUES ('PH208', 'Digital Electronics', 'B.Sc', 'Physics', 40, 2, 5);
INSERT INTO Subject VALUES ('PH210', 'Thermal Physics', 'B.Sc', 'Physics', 49, 2, 6);
INSERT INTO Subject VALUES ('PH402', 'Quantum Mechanics', 'B.Sc', 'Physics', 30, 4, 3);
INSERT INTO Subject VALUES ('PH404', 'Optics', 'B.Sc', 'Physics', 38, 4, 5);
INSERT INTO Subject VALUES ('PH406', 'Electronics', 'B.Sc', 'Physics', 32, 4, 5);
INSERT INTO Subject VALUES ('PH408', 'Statistical Mechanics', 'B.Sc', 'Physics', 40, 4, 2);
INSERT INTO Subject VALUES ('PH410', 'Solid State Physics', 'B.Sc', 'Physics', 45, 4, 2);
INSERT INTO Subject VALUES ('PH602', 'Particle Physics', 'B.Sc', 'Physics', 44, 6, 5);
INSERT INTO Subject VALUES ('PH604', 'Condensed Matter', 'B.Sc', 'Physics', 40, 6, 5);
INSERT INTO Subject VALUES ('PH606', 'Astrophysics', 'B.Sc', 'Physics', 42, 6, 4);
INSERT INTO Subject VALUES ('PH608', 'Advanced Electronics', 'B.Sc', 'Physics', 43, 6, 3);
INSERT INTO Subject VALUES ('PH610', 'Quantum Mechanics', 'B.Sc', 'Physics', 32, 6, 5);
INSERT INTO Subject VALUES ('CH202', 'Inorganic Chemistry', 'B.Tech', 'Chemistry', 37, 2, 4);
INSERT INTO Subject VALUES ('CH204', 'Organic Chemistry', 'B.Tech', 'Chemistry', 30, 2, 3);
INSERT INTO Subject VALUES ('CH206', 'Physical Chemistry', 'B.Tech', 'Chemistry', 45, 2, 3);
INSERT INTO Subject VALUES ('CH208', 'Analytical Chemistry', 'B.Tech', 'Chemistry', 32, 2, 5);
INSERT INTO Subject VALUES ('CH210', 'Biochemistry', 'B.Tech', 'Chemistry', 47, 2, 5);
INSERT INTO Subject VALUES ('CH402', 'Reaction Mechanisms', 'B.Tech', 'Chemistry', 36, 4, 3);
INSERT INTO Subject VALUES ('CH404', 'Spectroscopy', 'B.Tech', 'Chemistry', 44, 4, 5);
INSERT INTO Subject VALUES ('CH406', 'Chemical Thermodynamics', 'B.Tech', 'Chemistry', 39, 4, 5);
INSERT INTO Subject VALUES ('CH408', 'Chemical Kinetics', 'B.Tech', 'Chemistry', 30, 4, 5);
INSERT INTO Subject VALUES ('CH410', 'Quantum Chemistry', 'B.Tech', 'Chemistry', 40, 4, 5);
INSERT INTO Subject VALUES ('CH602', 'Electrochemistry', 'B.Tech', 'Chemistry', 42, 6, 4);
INSERT INTO Subject VALUES ('CH604', 'Polymer Chemistry', 'B.Tech', 'Chemistry', 36, 6, 2);
INSERT INTO Subject VALUES ('CH606', 'Surface Chemistry', 'B.Tech', 'Chemistry', 32, 6, 2);
INSERT INTO Subject VALUES ('CH608', 'Computational Chemistry', 'B.Tech', 'Chemistry', 40, 6, 5);
INSERT INTO Subject VALUES ('CH610', 'Nanotechnology', 'B.Tech', 'Chemistry', 45, 6, 2);
